// ────────────────────────────────────────────────────────────────
// Klook AI Hackathon · Season 1 data + Season 2 schedule
// ────────────────────────────────────────────────────────────────

const VIDEO_BASE = 'https://github.com/s860164/klook-cup-hackathon/releases/download/videos-v1/';

// 10 finalists. Award field: 'champion' | 'second' | 'third' | null
// Plus judge special award: 'kris' | 'liuYi' | 'poan' | 'louis' | null
window.S1_FINALISTS = [
  {
    id: 'weekend-finder',
    emoji: '🎫',
    title: 'Weekend Finder',
    builder: 'Tina',
    illo: 'assets/klook/illos/C168-adventure.png',
    accent: 'orange',
    award: 'champion',
    specialAwards: ['poan'],
    summary: 'A single-feed event discovery tool aggregating activities from Taiwan ticketing platforms — KKTIX, AccuPass, OpenRice and more.',
    description: 'AI categorizes events, generates plain-language summaries, and surfaces price + date details without platform-switching. A social group-plan feature lets friends RSVP together with no app download — just a shared link. Calendar integration + a 30-day rolling window for planning weekends in advance.',
    videoUrl: VIDEO_BASE + 'demo_09_Tina_Weekend_Finder.mp4',
    speechVideoUrl: VIDEO_BASE + 'award_1st_Tina_Weekend_Finder.mp4',
  },
  {
    id: 'home-cook',
    emoji: '🍳',
    title: 'Home Cook',
    builder: 'Willa',
    illo: 'assets/klook/illos/C111-night-market.png',
    accent: 'teal',
    award: 'second',
    specialAwards: ['liuYi', 'louis'],
    summary: 'A bilingual recipe app bridging the gap between Chinese families and non-Chinese-speaking domestic helpers.',
    description: 'Family members type a dish name in Chinese; AI generates full bilingual step-by-step recipes, illustrated ingredient lists (via Gemini), and YouTube tutorial links. Helpers filter by meal type and follow illustrated instructions. A review system lets families leave feedback in Chinese, auto-translated for the helper — helping them improve toward "Michelin standard" home cooking.',
    videoUrl: VIDEO_BASE + 'demo_10_Willa_Home_Cook.mp4',
    speechVideoUrl: VIDEO_BASE + 'award_2nd_Willa_Home_Cook.mp4',
  },
  {
    id: 'expense-tracker',
    emoji: '💰',
    title: 'Expense Tracker',
    builder: 'Charnie',
    illo: 'assets/klook/illos/C054-paying.png',
    accent: 'orange',
    award: 'third',
    specialAwards: [],
    summary: 'A two-part tool that automates Workday business expense filing. 16 receipts processed in under 1 minute vs. 30+ minutes manually.',
    description: 'Part 1 (web app): upload receipt images, AI organizes them into a Workday-compatible Excel — itemized by category, date, trip zone — flagging non-reimbursable items and generating a matched PDF packet. Part 2 (Chrome extension): auto-fills every Workday expense form field directly from uploaded receipt images.',
    videoUrl: VIDEO_BASE + 'demo_05_Charnie_Expense_Tracker.mp4',
    speechVideoUrl: VIDEO_BASE + 'award_3rd_Charnie_Expense_Tracker.mp4',
  },
  {
    id: 'miro-miro',
    emoji: '🎲',
    title: 'Miro Miro',
    builder: 'Yolanda',
    illo: 'assets/klook/illos/EBG001-team-highfive.png',
    accent: 'purple',
    award: null,
    specialAwards: ['kris'],
    summary: 'An interactive icebreaker game for online team building. Participants join via a shared link, answer AI-prompted questions, and react with emojis.',
    description: 'The session ends with an auto-generated summary highlighting the most engaged player and the most memorable answers — with a downloadable highlight report to help remote teams get to know each other better. Built for hybrid teams that want more than another awkward Zoom call.',
    videoUrl: VIDEO_BASE + 'demo_01_Yolanda_Miro_Miro.mp4',
  },
  {
    id: 'move-space',
    emoji: '💭',
    title: 'Move Space',
    builder: 'Janet',
    illo: 'assets/klook/illos/C031-celebrate.png',
    accent: 'teal',
    award: null,
    specialAwards: [],
    summary: 'A private, offline-first mobile app for emotional processing. No account, no server storage — everything stays on device.',
    description: 'Users type or speak how they feel; AI responds with warm, specific empathy. Unwanted entries can be ritually released via shredding, fire, or a release animation. Includes a 4-7-8 breathing guide, ambient sounds (rain, ocean, campfire), and a virtual plant that grows with consistent journaling.',
    videoUrl: VIDEO_BASE + 'demo_02_Janet_Move_Space.mp4',
  },
  {
    id: 'family-bite',
    emoji: '🍽',
    title: 'Family Bite',
    builder: 'Aish',
    illo: 'assets/klook/illos/C110-buffet-feast.png',
    accent: 'orange',
    award: null,
    specialAwards: [],
    summary: 'An AI-powered weekly meal planner for households with diverse dietary needs.',
    description: 'Each family member gets a profile capturing allergies, spice tolerance, calorie targets, and preferences. The app connects to favorite recipe blogs and generates a differentiated meal plan — separate lunches per person, shared dinners — all under 30 minutes prep time. Includes calorie + protein counts, a rating system to train future recommendations, and a shareable grocery list.',
    videoUrl: VIDEO_BASE + 'demo_03_Aish_Family_Bite.mp4',
  },
  {
    id: 'cat-food-tracker',
    emoji: '🐱',
    title: 'Cat Food Tracker',
    builder: 'Andy',
    illo: 'assets/klook/illos/C341-treasure-box.png',
    accent: 'gold',
    award: null,
    specialAwards: [],
    summary: 'A mobile app that tracks a cat\'s daily food intake using photo recognition.',
    description: 'Owners photograph each meal; AI identifies the food, estimates portion size, and assesses whether the intake is appropriate based on the cat\'s age, weight, and health profile. Daily logs build into trend reports with color-coded calendars showing nutritional balance over time. Also tracks vaccination records and health milestones.',
    videoUrl: VIDEO_BASE + 'demo_04_Andy_Cat_Food_Tracker.mp4',
  },
  {
    id: 'lumos',
    emoji: '📚',
    title: 'Lumos',
    builder: 'Manya',
    illo: 'assets/klook/illos/EBG015-idea.png',
    accent: 'purple',
    award: null,
    specialAwards: [],
    summary: 'A reading companion that turns book highlights into a visual knowledge map.',
    description: 'Users photograph annotated pages or paste quotes; AI extracts content, assigns themes, and builds a constellation-style mind map. Cross-book connections are surfaced automatically — such as a Stoic emperor and a Holocaust survivor sharing the same insight on inner resilience. Over time, Lumos learns reading patterns and recommends next books by thematic affinity rather than genre.',
    videoUrl: VIDEO_BASE + 'demo_06_Manya_Lumos.mp4',
  },
  {
    id: 'coach',
    emoji: '🎯',
    title: 'Coach',
    builder: 'Alea',
    illo: 'assets/klook/illos/C091-promotion.png',
    accent: 'teal',
    award: null,
    specialAwards: [],
    summary: 'An always-available AI life coach at a fraction of human coaching costs.',
    description: 'Onboarding captures the user\'s goals, ideal daily routine, and preferred coaching style (warm or tough-love). Daily activity logs — workouts, reading, screen time — feed a weekly Sunday reflection that surfaces patterns and progress. The coach delivers personalized affirmations and actionable nudges. Future phases: auto-sync with Apple Health, Screen Time, and calendar.',
    videoUrl: VIDEO_BASE + 'demo_07_Alea_Coach.mp4',
  },
  {
    id: 'youtube-digest',
    emoji: '📺',
    title: 'Daily YouTube Digest',
    builder: 'Lillian',
    illo: 'assets/klook/illos/C289-phone-booking.png',
    accent: 'gold',
    award: null,
    specialAwards: [],
    summary: 'A personalized morning YouTube briefing that refreshes automatically at 8 AM — instead of an algorithm-driven feed.',
    description: 'The tool pulls videos from user-selected topic channels and generates AI summaries for each. Users browse cards by topic + video length, read summaries to decide whether to watch now or save for later, and skip irrelevant content entirely — saving up to 6 hours of browsing time per day.',
    videoUrl: VIDEO_BASE + 'demo_08_Lillian_Daily_YouTube_Digest.mp4',
  },
];

// Judges with quotes + special award winners
window.S1_JUDGES = [
  {
    key: 'louis',
    name: 'Louis',
    photo: 'assets/people/Louis Li.png',
    quote: "In just two weeks, we solved some of the biggest questions in life that have lasted four centuries — what do I eat today, and what do I do on the weekend? A lot of us had basically no background in technology or AI. And now we know what AI is capable of. I believe that's probably the biggest prize for everyone who participated.",
    videoUrl: VIDEO_BASE + 'judge_04_Louis_Feedback.mp4',
    pick: { builder: 'Willa', project: 'Home Cook', projectId: 'home-cook' },
  },
  {
    key: 'poan',
    name: 'Poan',
    photo: 'assets/people/Poan Chen.png',
    quote: "What AI is changing here is that it makes it so easy for us to really bring these kind of crazy ideas to life. And all the ideas themselves become so important — those tiny daily problems we've just learned to live with? Now we can actually solve them.",
    videoUrl: VIDEO_BASE + 'judge_03_Poan_Feedback.mp4',
    pick: { builder: 'Tina', project: 'Weekend Finder', projectId: 'weekend-finder' },
  },
  {
    key: 'liuYi',
    name: 'Liu Yi',
    photo: 'assets/people/Yi Liu.png',
    quote: "I tried to play the role of a VC investor evaluating these projects. Whether the demand truly exists, whether it can scale, whether it has room to grow — and I was genuinely impressed.",
    videoUrl: VIDEO_BASE + 'judge_02_LiuYi_Feedback.mp4',
    pick: { builder: 'Willa', project: 'Home Cook', projectId: 'home-cook' },
  },
  {
    key: 'kris',
    name: 'Kris',
    photo: 'assets/people/Kris Chen.png',
    quote: "All the demos today were honestly super impressive — I may actually use some of these tomorrow.",
    videoUrl: VIDEO_BASE + 'judge_01_Kris_Feedback.mp4',
    pick: { builder: 'Yolanda', project: 'Miro Miro', projectId: 'miro-miro' },
  },
];

// Winner speeches — 3rd → 2nd → 1st reveal order
window.S1_WINNER_SPEECHES = [
  {
    rank: 'third',
    medal: '🥉',
    label: '3rd Place',
    builder: 'Charnie',
    project: 'Expense Tracker',
    projectId: 'expense-tracker',
    quote: "It makes me realize how capable AI is — and also the challenges it faces. It's not just the good side, but also the bottlenecks when we're building tools. I'm very lucky to be picked to participate in this hackathon, and I hope everyone on this call would have a chance to do that in future hackathons.",
    color: '#CC6600',
    speechVideoUrl: VIDEO_BASE + 'award_3rd_Charnie_Expense_Tracker.mp4',
  },
  {
    rank: 'second',
    medal: '🥈',
    label: '2nd Place',
    builder: 'Willa',
    project: 'Home Cook',
    projectId: 'home-cook',
    quote: "When I was in primary school, my dream was to do coding — but I never entered into this field. Right now, I feel like the dream has come true. I can just use natural language to build anything I want.",
    color: '#8E9AAA',
    speechVideoUrl: VIDEO_BASE + 'award_2nd_Willa_Home_Cook.mp4',
  },
  {
    rank: 'champion',
    medal: '🏆',
    label: 'Champion',
    builder: 'Tina',
    project: 'Weekend Finder',
    projectId: 'weekend-finder',
    quote: "I built Weekend Finder because I was tired of spending my whole Friday night figuring out what to do on Saturday. Now I win this award — while actually being on a weekend trip. I think that's the best proof that it works.",
    color: '#D4A017',
    speechVideoUrl: VIDEO_BASE + 'award_1st_Tina_Weekend_Finder.mp4',
  },
];

// Mentors — names only, no role
window.S1_MENTORS = [
  { name: 'Ryan Huang',  photo: 'assets/people/Ryan Huang.png' },
  { name: 'Andy Huang',  photo: 'assets/people/Andy Huang.png' },
  { name: 'Eden Kao',    photo: 'assets/people/Eden Kao.png' },
  { name: 'Wesley Fan',  photo: 'assets/people/Wesley Fan.png' },
  { name: 'Willy Wang',  photo: 'assets/people/Willy Wang.png' },
  { name: 'Page Deng',   photo: 'assets/people/Page Deng.png' },
];

// Season 2 judges — new panel. Photos provided; quotes TBD until S2.
window.S2_JUDGES = [
  {
    key: 'lynette',
    name: 'Lynette Dai',
    photo: 'assets/people/Lynette Dai.png',
    blurb: 'Watching out for ideas that make life genuinely easier — not flashier.',
  },
  {
    key: 'silas',
    name: 'Silas You',
    photo: 'assets/people/Silas You.png',
    blurb: 'Picking the demo I\'d actually open again on Monday.',
  },
  {
    key: 'emma',
    name: 'Emma Lee',
    photo: 'assets/people/Emma Lee.png',
    blurb: 'Rooting for the scrappy, half-finished build with the clearest story.',
  },
  {
    key: 'kenny',
    name: 'Kenny Tang',
    photo: 'assets/people/Kenny Tang.png',
    blurb: 'Where does AI quietly disappear into the workflow? That\'s the winner.',
  },
];

// Schedule
window.S2_SCHEDULE = [
  {
    date: 'Jun 24',
    day: 'Wed',
    accent: 'orange',
    title: 'On-site Training',
    tag: 'Closed-door',
    desc: 'Half-day onboarding for selected builders. Tool walkthroughs, environment setup, idea scoping with mentors. Attendance required.',
    illo: 'assets/klook/illos/EBG015-idea.png',
  },
  {
    date: 'Jun 25 – 28',
    day: 'Thu – Sun',
    accent: 'teal',
    title: 'Building + Mentor Sessions',
    tag: '4 days · async',
    desc: 'Build at your own pace. Mentors hold daily office hours and 1:1 slots. Roughly 4–12 hours of total work depending on your scope.',
    illo: 'assets/klook/illos/EBG001-team-highfive.png',
  },
  {
    date: 'Jun 29',
    day: 'Mon',
    accent: 'purple',
    title: 'Demo Day',
    tag: 'Open-door · Hybrid',
    desc: 'Afternoon showcase, on-site in Taipei with full online streaming. 5-min demo + Q&A per project. Can\'t come? Submit a pre-recorded video.',
    illo: 'assets/klook/illos/C031-celebrate.png',
  },
];
